name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-provider: basic
      - name: Build
        run: ./gradlew build --info
      - name: Publish unit test results (Ubuntu)
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always() && matrix.os == 'ubuntu-latest'
        with:
          files: "**/test-results/**/*.xml"
          comment_mode: off
          check_name: "Test Results (Ubuntu)"
      - name: Publish unit test results (Windows)
        uses: EnricoMi/publish-unit-test-result-action/windows@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always() && matrix.os == 'windows-latest'
        with:
          files: "**/test-results/**/*.xml"
          comment_mode: off
          check_name: "Test Results (Windows)"
      - name: Publish unit test results (MacOS)
        uses: EnricoMi/publish-unit-test-result-action/macos@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always() && matrix.os == 'macos-latest'
        with:
          files: "**/test-results/**/*.xml"
          comment_mode: off
          check_name: "Test Results (MacOS)"
